name: pharma-supply
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - sqlalchemy
  - psycopg2
  - numpy
  - joblib
  - xgboost
  - scikit-learn
  - shap
  - pip
  - pip:
      - fastapi
      - uvicorn
      - pydantic
      - python-dotenv
      - psycopg2-binary